export default {
  // payload: {
  //   verifyAs: '',
  //   userProfile: {
  //     name: 'Иван',
  //     surname: 'Иванов',
  //     patronymic: 'Иванович',
  //     passport: '4654-000000',
  //     nationality: 'ru',
  //     inn: '355135218579',
  //     familyStatus: 'single',
  //     snils: '',
  //   },
  //   images: {
  //     userPassport: null,
  //     userPassportActiveSubscription: null,
  //   },
  //   companyProfile: {
  //     name: 'Example company',
  //     inn: '7707308480',
  //     registrationAddress: 'Lenina 12, 83',
  //     bik: '044525225',
  //     site: '',
  //     realAddress: '',
  //     realAddressEqual: false,
  //     kpp: '27464537463453',
  //     ogrn: '1137746185818',
  //     okpo: '54245245',
  //     bank: 'OOO Sberbank',
  //     checkingAccount: '40702810300020038047',
  //     correspondingAccount: '30101810400000000225',
  //   },
  //   investPlatformAgreement: false,
  //   operatorAndInvestorAgreement: false,
  //   confirmResidentRf: false,
  //   personalAgreement: false,
  //   isCompany: 0,
  //   confirmationToken: '',
  //   questions: {
  //     finance: [],
  //     questionnaire: [],
  //   },
  // },
  payload: {
    verifyAs: '',
    userProfile: {
      name: '',
      surname: '',
      patronymic: '',
      passport: '',
      nationality: '',
      inn: '',
      familyStatus: '',
      snils: '',
    },
    images: {
      userPassport: null,
      userPassportActiveSubscription: null,
    },
    companyProfile: {
      name: '',
      inn: '',
      registrationAddress: '',
      bik: '',
      site: '',
      realAddress: '',
      realAddressEqual: false,
      kpp: '',
      ogrn: '',
      okpo: '',
      bank: '',
      checkingAccount: '',
      correspondingAccount: '',
    },
    investPlatformAgreement: false,
    operatorAndInvestorAgreement: false,
    confirmResidentRf: false,
    personalAgreement: false,
    isCompany: 0,
    confirmationToken: '',
    questions: {
      finance: [],
      questionnaire: [],
    },
  },
  errors: {
    userProfile: {
      name: null,
      surname: null,
      patronymic: null,
      passport: null,
      nationality: null,
      inn: null,
      familyStatus: null,
      snils: null,
      isCompany: null,
    },
    images: {
      userPassport: null,
      userPassportActiveSubscription: null,
    },
    companyProfile: {
      name: null,
      inn: null,
      registrationAddress: null,
      bik: null,
      site: null,
      realAddress: null,
      realAddressEqual: null,
      kpp: null,
      ogrn: null,
      okpo: null,
      bank: null,
      checkingAccount: null,
      correspondingAccount: null,
    },
    investPlatformAgreement: false,
    operatorAndInvestorAgreement: false,
    confirmResidentRf: false,
    personalAgreement: false,
    confirmationToken: null,
    questions: {
      questionnaire: false,
    },
  },
}
